# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=36)),
                ('workout_start_date', models.DateTimeField(verbose_name='date started')),
                ('workout_end_date', models.DateTimeField(verbose_name='date finished')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workout.Patient'),
        ),
    ]
